apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers
    version: v1
  name: customers
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: customers
      version: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: customers
        version: v1
    spec:
      containers:
      - image: th3nu11/istio-example:customer-service
        imagePullPolicy: Always
        name: istio-example
        resources:
          requests:
            memory: "40Mi"
