apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-example-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  number: 80
            path: /api/v1/orders/
          - pathType: Prefix
            backend:
              service:
                name: customers
                port:
                  number: 80
            path: /api/v1/customers/
          - pathType: Prefix
            backend:
              service:
                name: products
                port:
                  number: 80
            path: /api/v1/products/
