apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders
    version: v1
  name: orders
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
        version: v1
    spec:
      containers:
        - image: th3nu11/istio-example:order-service
          name: istio-example
          imagePullPolicy: Always
          resources:
            requests:
              memory: "40Mi"
          env:
            - name: CUSTOMERS_SERVICE_HOST
              value: http://customers:80
            - name: PRODUCTS_SERVICE_HOST
              value: http://products:80

