apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: products
    version: v1
  name: products
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: products
  strategy: {}
  template:
    metadata:
      labels:
        app: products
        version: v1
    spec:
      containers:
      - image: th3nu11/istio-example:product-service
        imagePullPolicy: Always
        name: istio-example
        resources:
          requests:
            memory: "50Mi"

