apiVersion: v1
kind: Service
metadata:
  labels:
    app: products-beta
  name: products-beta
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: products
    version: beta
