apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: production-mtls-strict
  namespace: orders
spec:
  selector:
    matchLabels:
      app: products
  mtls:
    mode: STRICT